### ISSUE TITLE
Missing components of Sample Dataset?

### ISSUE THREAD

**Issue by agentmess** [PulmonaryMRI/imoco_recon#4]
From user:
The matlab code is trying to load a “_mrL.cfl” and a “_maps.cfl” file which don’t seem to be part of the sample data. Are these somehow included in the “_imoco.cfl” file?

**Comment by Phillistan16** [comment]
For python implementation, `_mrL.cfl` can be generated by `recon_xdgrasp.py`, and `_maps.cfl` is not required.
For Matlab version, `_mrL.cfl` can be generated by `mc_mr_recon.sh`, and `_maps.cfl` by `mc_prep_recon.sh`.
