### ISSUE TITLE
How do I obtain raw data in .cfl format to use with this code?

### ISSUE THREAD

**Issue by mscipio** [PulmonaryMRI/imoco_recon#9]
Hi,

I was checking the code in this repo, and while I am somehow familiar with `sigpy` and the other libraries being used, I was hoping to find a way to convert raw data exported from the scanner (in my case a `Siemens mMR`, so files in `twix` format) to `.cfl` that I can then import and use with this code.

Do you have any suggestions about this?

Thank you!

**Comment by nicholas-zhu** [comment]
Hi,

.cfl basically is a binary file, and .hdr logs the dimension information of the data, and .cfl is in complex128.
The transformation is actually very straightforward. Please find the source code from BART.

https://github.com/mrirecon/bart/blob/master/python/cfl.py

Best,
Xucheng

**Comment by mscipio** [comment]
Hi,
thank you for the reply.
I am aware of what cfl files are and of that function provided by BART, but I was asking more of a way to process `.dat` files directly exported from the MR scanner (at least in my case of a Siemens scanner). You need a way to decode those proprietary raw data files so that you can then convert them into cfl ...

**Comment by ltorres6** [comment]
Hi mscipio, you will need to read the data into either MATLAB or python using whichever tools you typically would use (vendor dependent) and then save the files as cfl. BART has some functionality for Siemens data I believe (twixread), which would be most convenient. If that doesn't work you can try this python package (https://github.com/pehses/twixtools).
Hope this helps.
